---
title: ''
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

\section*{Acknowledgements}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; First and foremost, I would like to express my gratitude to our ocean for the generosity it bestows upon us daily and for the awe it instilled in me as a young child—a wonder that has grown into a lifelong dream and pursuit. I am deeply grateful to Dr. Nyssa J. Silbiger, my advisor, for her unwavering support, encouragement, inspirational attitude, and collaboration on this project. Thank you for believing in me, urging me to become the person I need to be, equipping me with the knowledge, tools, and skills needed to achieve this, and for ignoring the lies we often tell ourselves about ourselves. To my thesis committee, Dr. Peter J. Edmunds and Dr. Kerry J. Nickols, thank you for your invaluable guidance and advice throughout this process. Thank you to my mentors, Dr. Aradhna Tripati, Dr. Rachel Bay, Dr. Tessa Hill, and Dr. Melanie Okoro, who have acted as academic mothers, paving the way and uplifting me throughout my academic trajectory. I would also like to extend my gratitude to the Silbiger and Nichols Lab team, including D.M. Barnas, J.R. Kerlin, C. Fajardo, and H. Merges. In particular, I want to give a special thank you to J.B. Fields and T. Smith for their monumental support and dedication in ensuring that everything ran smoothly inside and outside of the lab; they were always there as friends to call on and played pivotal roles in ensuring the success of my degree. Without all of you, none of this would have been possible. Throughout endless sleepless nights and days of struggle, thank you for lifting as you climbed. A special thank you to Ana and the rest of the custodial staff, whose skills are the cornerstone of the entire institution, and whose presence makes the halls of academia feel more like home as they sweep through the halls, serenaded by the rhythm of bachata. This research couldn’t have been possible without the financial support from the National Science Foundation Graduate Research Fellowship Program, UCLA Center for Diverse Leadership in Science Early Career Fellowship, UC Davis Sustainable Oceans Scholars Program, and the National Science Foundation CAREER grant OCE-2044837 awarded to Dr. Nyssa Silbiger, the material in this study based upon work supported by the U.S. National Science Foundation, the CSUN Department of Biology, and research activities that were conducted under scientific collecting permits issued by the California Department of Fish and Wildlife (ID: S-220520002-22054-001).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I extend my heartfelt gratitude to my family, Robert K. Dellinger and Ana. C. Dellinger, for instilling in me the belief that education is the most powerful tool. They have made me feel capable of achieving anything I set my mind to and have unwaveringly supported my dreams, regardless of their nature. To my father, thank you for raising me with the understanding that everything we create must be done with love; love is the secret ingredient. To my mother, I am forever thank you for sacrificing your own dreams and for persevering through the challenges of the ingratitude of the nation in which you settled, all to ensure that I could pursue my own dreams and aspirations.Thank you to all of those who have parented me and the push of the universe for laughing at me. Thank you to my chosen family, including my partner and friends, who immersed me in a queerness that dominant systems cannot understand, who illuminated alternative paths from the outdated paradigms we are entangled in, and who remember to swim despite everything. Their love and resilience have nurtured me and imbued me with the buoyancy and fortitude to demand better from the world around me. Thank you for your willingness to churn the waters up, for being holders of wisdom and knowledge, and for showing me that the facts of nature often falsify the prevailing theories. I would not be here today without their love and support. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Being a part of the CSUN and the Los Angeles community the past three years has been some of the most formative and fulfilling experiences of my life and for my career moving forward. Studying climate change in an era marked by rapid ecological change and numerous interconnected crises, encompassing racial capitalism and the climate emergency, particularly during a time in which society stands at a pivotal crossroads for humanity's future can feel rather dismal. Yet the support and knowledge I've received from my community and mentors as well as the collective imagination of the communities I am a part of has instilled within me an unbridled sense of optimism. That amid these challenges, we possess all of the solutions to the crises we face, and that within our collectivities, there are reservoirs of hope for the future - a future where our individual lives matter not less, but more, as they form the pixels shaping a panorama of endless change.
