---
title: ''
output: pdf_document
---


# Discussion

Better understanding the impacts of global climate change on marine ecosystems requires us to think outside the confines of direct impacts (Kroeker et al., 2012) since individual alterations in organismal physiology have much larger implications for communities (Kroeker et al., 2012; Gaylord et al., 2015).These results presented in this thesis highlight the importance of considering the physiological and geochemical interactions between temperature and carbonate chemistry when interpreting species' vulnerability to OA, as multiple drivers of ecological change may interact in myriad ways. This study also illustrates the use of thermal performance curves as a mechanistic way to tease apart multiple drivers of ecological change to make more accurate predictions of species' vulnerability to future climate change.Understanding changes in metabolic rates to different magnitudes and combinations of abiotic drivers may elucidate complex changes in physiological mechanisms that are unable to be uncovered using a few treatments (Becker and Silbiger, 2020; Edmunds et al., 2011).

urther, assessing the interactive effects warming and pH using a performance curve approach may help us better understand how performance curves change shape with the inclusion of other abiotic factors, which have been explored through other mechanistic approaches such as the Oxygen and Capacity-Limited Thermal Tolerance concept (Pörtner, et al. 2017). Therefore, performance curves should be utilized through a comparative lens to better understand the role that pH has on thermal performance to create novel approaches to quantify and categorize performance under a range of pH conditions.It is expected that ocean acidification will impose additional energetic costs through physiological stress and therefore narrow the breadth and optimum of the curve (Pörtner 2008; Gaylord et al., 2015). The ability for organisms to respond to anthropogenic-induced acidification depends on species level acid- base regulation and will result in increased energy demand and respiration rates (Pörtner, 2008). Measuring organism responses to a range of pH in the presence or absence of thermal stress may also provide information regarding how temperature may impact performance under differing pH environments. 

One possible explanation for this phenomenon is that the increased metabolic rate exhibited by \textit{T. funebralis} serves as a compensatory response to the adverse conditions induced by ocean acidification. In the case of \textit{T. funebralis}, it is plausible that the species is augmenting its metabolic rate as a means of upholding vital functions and maintaining homeostasis amidst acidic conditions. Another mechanism could be the upregulation of metabolic pathways that generate ATP, the energy currency of cells, to meet the increased energy demands at higher temperatures. This is consistent with the findings of other studies that have shown elevated metabolic rates in gastropods or decreases in body size associated with increased temperture Ccitation). Turban snails found at lower latitudes of the coastline grow smaller at a faster rate as well as live longer than those found at higher latitudes (Frank, 1975); falling in line with the metabolic theory of ecology and the expected decrease in body size under higher temperatures (Brown et al., 2004). Research by Elahi (2020) illustrates decreasing gastropod shell size over the past few decades and expectations for changes in the future. It is therefore imperative to understand the direct and indirect implications of shrinking shell sizes on organisms.

The present study found that the respiration rate of \textit{T. funebralis} is highly dependent on temperature, with the highest respiration rate occurring between 20-22°C, consistent with other thermal performance studies of the species (somnero). The present study also found that the effects of OA on respiration rate are highly dependent on temperature. Although high CO$_2$ increased respiration rate at 20°C, this effect gradually lessened with successive warming to 20°C, illustrating how moderate warming might be able to mediate the effects of OA through temperature's effects on both physiology and seawater geochemistry. Furthermore, other studies on the energy budget and transfer of \textit{Tegula funebralis} indicate that rates of aquatic and aerial respiration differ, with low intertidal individuals respiring at a rate of 75 µl O$_2$/hr in water and 43 µl/hr in air cite(paine1969). The large- scale spatial gradient and relatively heterogeneous environment of the Pacific coast, as well as the wide biogeographic distribution of the Tegula genus species specific evolution to particular zonations make them the Darwins finches of thermal ecology. It has been found that \textit{T. funebralis} has a wider thermal tolerance range compared to its congeners, \textit{T. brunnea} and \textit{T. montereyi}, which inhabit lower intertidal and subtidal zones \cite{tomanek1999evolutionary}. However, this is precisely what might make \textit{T. funebralis} more vulnerable to future changes of a few degrees as it already withstands drastic temperature fluctuations within the intertidal.

This study lso discovered that there will be changes in the energy budget of \textit{Tegula} as a result of ocean acidification and warming, which could have consequences on other specie in the intertidal. Slight changes within the energy budget of this ubiquitous species could have downstream consequences in terms of energy transfer, as the rate of annual consumption by \textit{Tegula} is estimated to be 1,071 kcal m$^{-2}$ yr$^{-1}$ while the net primary production is estimated to be about 1,167 kcal m$^{-2}$ yr$^{-1}$, with about 60% of energy transferred, illustrating the important role \textit{Tegula} play in both balancing intertidal ecosystems but also in transferring energy throughout the ecosystem cite(paine19710). The macroalgal-herbivore interaction,is of prime importance as it is the primary pathway for energy to move through trophic levels and is predicted to change under projected ocean warming and acidification (O'Connor et al., 2009). Alterations within metabolic rates of performance such as respiration, calcification, and growth attributed to climate change will ultimately affect net ecosystem production, net ecosystem calcification, and food web dynamics.
