---
title: ''
output:
  pdf_document: default
---


# Methods 

\vspace{0.5cm}

## (1) Mesocosm Design  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Silbiger Lab mesocosm system at California State University, Northridge was used to emulate experimental conditions of a semi-diurnal tidal fluctuation across a gradient of temperatures and blocked exposure to either low or high pH. The facility operated as a closed-loop system, wherein water from individual tanks was continuously recirculated back into a central holding reservoir (sump). Unbuffered natural seawater was collected from the Southern California Marine Institute (SCMI) in San Pedro, CA and filtered through three mesh filters (20 $\mu$m, 5 $\mu$m, 1 $\mu$m) prior to being introduced into the sump of the mesocosm system. Within the system, recirculating seawater underwent further filtration through three 50 $\mu$m carbon bag filters, eight mesh filters, a UV sterilizer (Comet Series 95 Watt Lamp), and a chiller (Aqua Logic Delta Star, DS-4) which maintained water quality and chilled seawater to ambient conditions. Weekly water replacements, accounting for approximately 50% of the total volume, were conducted to prevent the accumulation of metabolic waste and to maintain stable carbonate parameters within the system. The mesocosm system was equipped with 16 experimental tanks (53.9 cm (L) × 31.75 cm (W) × 34.29cm (H)) with individual controls for temperature, light intensity, and water flow. Each tank was outfitted with a submersible powerhead pump (Hydor Nano Koralina 240 powerhead, 240 GPH), 200 W Heater (Hydor aquarium heater), temperature probe (Neptune Systems, ±0.1 degree C), pH probe (Neptune Systems, Lab Grade Double Junction, measures pH from 4.0 to 12.0 ±0.1), three flow sensors (Apex, FS25 ¼” fitting, flow rates from 3-12 GPH (12-24 LP)), and a temperature logger (HOBO TidBit MX2203, ±0.2 degree C). LED lights (Halo Basic M-110) in each tank followed a 12:12 day/night cycle, which mimicked the local light conditions using a sunset and sunrise table. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Each individual tank was programmed to experience tidal fluctuations as well as temperature/pH controlled seawater conditions for their respective treatments. Programmable solenoid valves (Apex Neptune) were utilized to adjust the seawater flow rates to each tank, ensuring that either inflow rates exceeded outflow drain rates simulating a high tide condition or outflow drain rates exceeded inflow rates to simulate a low tide condition. This emulation aimed to replicate the semi-diurnal tidal characteristic of the Pacific Coast. Within a 24-hour period, two high tide and two low tide fluctuations, each lasting six hours, were generated by either opening or closing the solenoids. Flow rates were meticulously maintained on a daily basis using a graduated cylinder and timepiece to ensure a programmable inflow of 10 L/h, constant total inflow of 10 L/hour, and a constant outflow drain rate of 15 L/hour, thereby creating the desired tidal effect. Precise control over temperature in each tank was achieved by employing a programmable thermostat (Neptune Apex), which automatically activated or deactivated heaters in response to temperature deviations from the set range. Individual tank pH levels were regulated using a pH-stat set-up through the direct bubbling and mixing of CO2 facilitated by a pH logger and solenoid valves (Neptune system) attached to a CO2 tank (PhosBan Reactor 150). Additionally, in each tank, a venturi connected to an aquarium pump facilitated the mixing of ambient air to stabilize the pH levels in the treatment tanks. After recirculation into the sump system, the sweater was chilled to ambient condition and scrubbed of CO2 using a phosban reactor (Phosban 150 Reactor). 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Throughout the experiment, various water quality parameters were regularly measured to monitor environmental conditions within the tanks. pH, dissolved oxygen (DO), and temperature were assessed daily at consistent times to ensure accurate readings and facilitate the calibration of in-tank temperature probes for precise measurements. pH and dissolved oxygen levels were measured daily, within each tank using a Termo Specific ORION ISE instrument with a resolution of 0.1 mV and an accuracy of ±0.2 mV or ±0.05%. Simultaneously, temperature readings were obtained using a Thermo Fisher Trace digital thermometer. The temperature data also aided in calibrating the thermostat sensors within each tank, which were adjusted once a day to maintain accurate temperature control. pH on the total scale was calculated from mV and temperature by using a multipoint calibration to a tris standard solution from the Dickson Lab at Scripps Institution of Oceanography following Dickson SOP 6a \cite{dickson2007guide}. Accuracy of the pH was tested against a Tris buffer of known pH from the Dickson Lab at Scripps Institution of Oceanography \cite{dickson2007guide}. The pH values for the individual aquaria were calculated using the seacarb package in R, accounting for temperature corrections specific to each tank \cite{gattuso2015package}. I also measured total alkalinity (TA) from water samples collected once every few days (3-4 days) from each experimental tank and sump. All total alkalinity (TA) water samples were collected and stored in 125 ml Nalgene containers. Prior to use, these containers underwent thorough cleaning in a 10% HCl bath for 24 hours, followed by rinsing with deionized (DI) water. Additionally, during sample collection, the containers were rinsed three times with sample water to ensure a representative water quality sample. Collected samples were analyzed within 24 hours of collection using a T-5 automatic titrator (Mettler Toledo) following the best practices for ocean CO2 measurements \cite{dickson2007guide}. To verify accuracy, a certified reference material (Reference Material for Oceanic CO2 Measurements, A. Dickson, Scripps Institution of Oceanography) was run prior to each total alkalinity measurement with an error no greater than 1.0% off from the certified value \cite{dickson2007guide}. 

### INSERT TABLE. Summary statistics (means ± SE) for tank parameters at each of the three timepoints. 

## (b) Species Collection and Maintenance

### INSERT FIGURE 2 MAP

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For this experiment, black turban snails (\emph{Tegula funebralis}) (N=80 individuals) were collected haphazardly from tidepools in Point Fermin, San Pedro, CA (Figure 2.) on August 16, 2022 (SCP ID: S-220520002-22054-001). All collections were made and transported during low tide to minimize any physiological variation that might be related to endogenous tidal rhythms. Individuals of \emph{T. funebralis} were measured for shell width (dorsal to ventral) between 18-22 mm using Vernier calipers, since shell height is a reliable predictor for body mass. Organisms were then transported back to California State University, Northridge in a wet insulated container where they were measured for blotted wet mass (g), volume displacement (mL), shell height (mm), and shell width (mm) and tagged using a previously weighed FloyTag placed at the apex of the dorsal side of the shell with coraffix glue. The snails were then randomized and assigned to an experimental treatment as detailed below. Each snail was randomly assigned to one of 16 experimental aquaria across a range of 8 temperatures from 12 to 26 °C and two pH treatments, and placed into their respective experimental tanks (n=4 per treatment). To adjust the snails to their treatment temperatures, all snails started in ambient temperature conditions (16 degree C), and temperatures were then increased or decreased at a rate of up to 2 º degree C per day until reaching the set treatment temperature. The changes in pH for the acidification treatments were simultaneously reduced with temperature changes at a rate of up to ~0.5 units per day during this period as this is the fluctuation of pH that organisms in the intertidal experience in a single day \cite{jellison2016ocean}. Organisms were adjusted to experimental conditions for a week before the experiment began. Throughout the experiment, snails were fed giant kelp wrack \emph{Macrosystis pyrifera}, a highly preferred food, was collected from Point Fermin, CA to feed organisms and placed on 3 inch PVC disks every three days throughout the experiment. \emph{M. pyrifera} was rinsed with fresh water to remove epiphytes prior to feeding. 

## (c) Temperature and pH Treatment 

### INSERT FIGURE 2 SST AND PH FROM NEARBY SHORE STATION SCOSS AND CITE 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sea snails were subjected to one of eight temperatures ranging from 12-26 degree C (12, 14, 16, 18, 20, 22, 24, 26; n=8) and either low or high pH conditions (7.7 or 8.0; n=2), resulting in 16 experimental treatments.  based on average facility tank temperatures, or a realistic marine heatwave occurring on top of ambient conditions. Nine tanks (three tanks per size class) underwent a marine heatwave manipulation, while the remaining nine tanks were maintained at ambient controls. Temperature conditions were chosen based on sea surface temperature ranges and variability at a nearshore shore station. pH was chosen due to the expected decreases of pH expected under future conditions.

## (d) Survivorship

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Snail survivorship was monitored daily during the experiment. Snails that exhibited signs of distress, such as being unable to adhere to tank surfaces, being found at the bottom of the tank, or showing no movement for a period of 24 hours, underwent sensory tests to assess potential mortality. Specifically, snails were gently held w and touched along their foot with forceps. If there was no response within thirty seconds, they were considered deceased and subsequently removed from the tank. Additionally, olfactory cues were also considered as indicators of potential mortality.

## (e) Metabolic Experiment

## Figure 2.4. Wet weight (g) to organic biomass (ash free dry weight; AFDW (g)) curve from preliminary trial used to calculate dry weight of the 90 experimental abalone (y = 0.093x + 0.049, R² = 0.98).  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Respiration rates were measured after a 7-day adjustment period and a 10-day exposure to the treatment conditions. Prior to conducting respirometry, each individual snail shell was thoroughly scrubbed using an acrylic brush to remove any epibiont communities that could potentially obscure respiration rates. Snail respiration rates were assessed by measuring oxygen evolution within sealed, water-tight respirometry chambers (650 mL) for each individual. A mesh wire separated the top and bottom sections of the chamber, with a magnetic stir bar (200 rpms) placed in the bottom section to ensure proper mixing of water and prevent oxygen stratification. During the respirometry trials, temperature was carefully controlled and stabilized using an insulated container and a programmable thermostat system (Apex Controller, Neptune Systems ± 0.1 degree C). Temperature adjustments were made using a submersible water heater (Finnex 300W Titanium Heater) and a water chiller (Aqua Logic Delta Star, DS-4). Oxygen measurements were taken at a frequency of 1 Hz using an oxygen probe (Presens fiber optic oxygen dipping probe, DP-PSt8 ± 0.1 degree C) and continuously monitored throughout the 45-minute respirometry trial using Presens Software. To ensure experimental consistency, four organisms from each pH treatment (n= 8 snails) and one blank control from each pH treatment (n = 2 blanks) were run together at the same treatment temperature. This resulted in a total of 10 individual chambers placed in the respirometry stand and measured simultaneously. Each chamber was fully submerged within the water bath to maintain a controlled temperature inside. Since each respiration chamber functioned as a sealed system, the oxygen consumption rate of each individual organism ($(\mu mol \: O_2 \: g^{-1}h^{-1})$) was calculated and normalized to ash free dry weight. To obtain final wet mass, snails were blotted with a paper towel to remove excess water, scrubbed with a toothbrush to remove epibiont communities, and then weighed using an electronic balance to the nearest 0.0001 g. Organic biomass and ash free dry weight was obtained after the experiment, during which snails were placed in a drying oven (Fisher Scientific Isotemp Drying Oven) at 60°C for 72 hours and then in a muffle furnace (Fisher Scientific Isotemp Muffle Furnace) set to 450°C for 5 hours.

## (f) Statistical analyses
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To analyze the thermal performance curves of respiration rates and determine the shape, we used the Sharpe Schoolfield high activation energy model. statistical analysis was conducted in R software. The Schoolfield model is widely used to describe the thermal performance curves of biological rates of ectotherms. the Schoolfield model was implemented in R to fit the data and estimate the parameters of the model.  The fitting process involved using the nmls and rTPC packages in R to optimize the model parameters and estimate their uncertainty \cite{padfield2021rtpc}. The data were fitted to the Sharpe Schoolfield model (high) using AIC values between relevant performance models for ectotherm species to evaluate the model's performance and the quality of the fit.  Furthermore, model selection techniques, such as comparing different models based on their statistical criteria (e.g., AICc), were employed to identify the most suitable model (e.g., gaussian, sharpe-schoolfield low, sharpe-schoolfield full, sharpe-schoolfield high, weibull) that accurately described the observed thermal performance curve. Furthermore, I conducted bootstrap resampling to estimate confidence intervals for the model predictions.

